//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Asistencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencias
    {
        public int id_asistencia { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> minutos_retraso { get; set; }
        public bool justificacion { get; set; }
        public string observacion { get; set; }
        public Nullable<int> id_docente { get; set; }
        public Nullable<int> id_grupo { get; set; }
    
        public virtual Docentes Docentes { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
