//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Asistencia.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sueldos
    {
        public int id_sueldos { get; set; }
        public int id_docente { get; set; }
        public int gestion { get; set; }
        public int mes { get; set; }
        public decimal haber_basico { get; set; }
        public decimal descuento { get; set; }
        public decimal liquido_pagable { get; set; }
    
        public virtual Docentes Docentes { get; set; }
    }
}
